[Theme]
DisplayName=MaxRegnerUI Solid
ThemeId={MAXREGNER-SOLID-001-2024}

[Control Panel\Desktop]
Wallpaper=%windir%\AtlasModules\Wallpapers\maxregnerui-solid.png
Pattern=
MultimonBackgrounds=0
PicturePosition=10
TileWallpaper=0
WallpaperStyle=2
PatternColor=

[Control Panel\Cursors]
AppStarting=%SystemRoot%\cursors\aero_working.ani
Arrow=%SystemRoot%\cursors\aero_arrow.cur
Hand=%SystemRoot%\cursors\aero_link.cur
Help=%SystemRoot%\cursors\aero_helpsel.cur
No=%SystemRoot%\cursors\aero_unavail.cur
NWPen=%SystemRoot%\cursors\aero_pen.cur
SizeAll=%SystemRoot%\cursors\aero_move.cur
SizeNESW=%SystemRoot%\cursors\aero_nesw.cur
SizeNS=%SystemRoot%\cursors\aero_ns.cur
SizeNWSE=%SystemRoot%\cursors\aero_nwse.cur
SizeWE=%SystemRoot%\cursors\aero_ew.cur
UpArrow=%SystemRoot%\cursors\aero_up.cur
Wait=%SystemRoot%\cursors\aero_busy.ani
DefaultValue=Windows Default
Crosshair=
IBeam=

[Sounds]
SchemeName=No Sounds

[VisualStyles]
Path=%windir%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XFF004488
SystemMode=Dark
AppMode=Dark
VisualStyleVersion=10
Transparency=1

[MasterThemeSelector]
MTSM=RJSPBS

[Boot]
SCRNSAVE.EXE=

[Metrics]
MinAnimate=1

[Icons]

[TrayNotify]

[CoolBar]

[Desktop]

[Global]

[WindowMetrics]
BorderWidth=-15
CaptionFont=Segoe UI, 9
CaptionHeight=23
CaptionWidth=23
IconFont=Segoe UI, 9
IconMetrics=16,16,0,0,16,16,0,0,32,32
IconTitleWrap=1
MenuFont=Segoe UI, 9
MenuHeight=21
MenuWidth=21
MessageFont=Segoe UI, 8
MinAnimate=1
PaddedBorderWidth=4
ScrollHeight=17
ScrollWidth=17
Shell Icon BPP=4
Shell Icon Size=32
Shell Small Icon BPP=1
Shell Small Icon Size=16
SizingBorderWidth=4
SmallCaptionFont=Segoe UI, 9
SmallCaptionHeight=20
SmallIconMetrics=16,16,0,0,16,16,0,0,32,32
SmallIconTitleWrap=1
StatusFont=Segoe UI, 8
ToolTipFont=Segoe UI, 8
